
version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
  Portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9001:9001
  apitests:
      image: sumitbhatia101/star:latest # Replace with 'sumitbhatia101/star:arm64' for arm/64/v8 or aarch64 chipsets 
      container_name: apitestsrest
      depends_on:
       kibana:
        condition: service_started
      entrypoint: sh -c "until curl -sSf http://kibana:5601; do sleep 15; done && mvn clean test"
      environment:
      - HOST_IP=PLACEHOLDER # Replace with the actual private IP address
      command: ["java", "-cp", "/app", "getLocalIPAddress"]
      ports:
        - 8082:8082
